### PR TITLE
Add grafana-loki tool to agent

### PR DESCRIPTION
**Pull request by maaharko**
Add grafana-loki tool to agents

### CODE REVIEW

**Comment by joinemm** [comment]
why the `flake.lock` update?

**Comment by maaharko** [comment]
Removed update of `flake.lock`

**Comment by joinemm** [comment]
You should also squash and rebase your commits into one instead of having revert commits

**Review by joinemm — APPROVED** [review]

**Comment by joinemm** [comment]
deployed to all testagents

**Pull request merged**
