### PR TITLE
remote x86 hydra builder: Add Yubikey provisioning

### PR DESCRIPTION
**Pull request by mkaapu**
- Environment for Yubikey provisioning (legacy Hydra builds)
- Add Yubikey signer accounts for build3 and build4

### CODE REVIEW

**Comment by mkaapu** [comment]
Provides environment for provisioning Yubikey as described here:
https://github.com/tiiuae/scs-pki-research/tree/main/yubikey

As Hydra is legacy system, this is not full automation of signing server with Nix, just providing environment where signing server can be set.

Tested on build4 Ficolo machine.

**Review by tervis-unikie — CHANGES_REQUESTED** [review]
Incorrect subject capitalization.
Take githooks into use and check github actions for warnings when making a PR.

**Review by alextserepov — APPROVED** [review]

**Comment by mkaapu** [comment]
> Incorrect subject capitalization. Take githooks into use and check github actions for warnings when making a PR.

Thanks Tervis for reminding. I rebased with main, installed git hooks and fixed commit subject.
However, commit message checking seems to fail for some other reason:
```
Error: Failed to retrieve commits (https://api.github.com/repos/tiiuae/ghaf-infra/pulls/80/commits)
589
Error: API rate limit exceeded for 20.172.5.33. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
590
Error: Process completed with exit code 7.
```

**Comment by mkaapu** [comment]
OK. I just re-run commit message check. It was just probably some internal GitHub error. Maybe too many checks running parallel, no idea really..
But check passed with re-run.

**Review by tervis-unikie — APPROVED** [review]

**Review by cazfi — APPROVED** [review]

**Pull request merged**
