### PR TITLE
Bug fix awsarm grafana alert.

### PR DESCRIPTION
**Pull request by karim20230**
-This update addresses the bug in the Grafana monitoring alerts for our awsarm env
-The bug fix ensures that alerts are now generated correctly, improving system monitoring and reliability.

### CODE REVIEW

**Comment by karim20230** [comment]
Fyi: this changes not yet deployed!

**Comment by mkaapu** [comment]
Please fix the commit message.

**Comment by karim20230** [comment]
> Please fix the commit message.

good catch marko! Done

**Comment by mkaapu** [comment]
> > Please fix the commit message.
> 
> good catch marko! Done

It is still not following the imperative mood:
https://ssrc.atlassian.net/wiki/spaces/SP/pages/280953024/Commit+message+format

Check passes but gives this:
Warning: Subject capitalization might not be correct

**Review by mnokka — APPROVED** [review]
Logical change , go ahead

**Review by joinemm — APPROVED** [review]

**Pull request merged**
