### PR TITLE
Add initial monitoring server configuration

### PR DESCRIPTION
**Pull request by joinemm**
Adds monitoring VM running Grafana and Prometheus, that monitors build4 and binarycache using node_exporter metrics

### CODE REVIEW

**Review by henrirosten — APPROVED** [review]
Approved, but I have not tested this.
@joinemm :
I assume you get a warning on installing the new monitoring configuration, since it doesn't have `secrets.yaml`, so the host key decryption should fail: https://github.com/tiiuae/ghaf-infra/blob/68318451901453382a21321316eb6d8e534986a3/tasks.py#L277

**Comment by joinemm** [comment]
@henrirosten I actually never saw this warning when testing, I was not aware secrets were required

**Comment by henrirosten** [comment]
> @henrirosten I actually never saw this warning when testing, I was not aware secrets were required

It's strictly not required, but if there's no `ssh_host_ed25519_key` for the given nixosconfig, `install` task should issue a warning and ask confirmation from the user. If that's not what happens, then it's probably an error in tasks.py.

**Comment by joinemm** [comment]
added secrets and tested with `install` task

**Comment by henrirosten** [comment]
You are missing a license for the new secrets.yaml, you should add secrets.yaml.license similarly to other host configs:

> WARNING  'reuse lint':
> MISSING COPYRIGHT AND LICENSING INFORMATION
> 
> The following files have no copyright and licensing information:
> * hosts/monitoring/secrets.yaml

**Review by henrirosten — APPROVED** [review]

**Pull request merged**
