### PR TITLE
Change cache.vedenemo.dev public key to new nixos cache

### PR DESCRIPTION
**Pull request by joinemm**
To be merged when we switch over to the new cache.

### CODE REVIEW

**Review by henrirosten — COMMENTED** [review]
Can you include this same change to the 'azarm' (aarch64 Ubuntu builder) configuration, which is currently in a shell script at: https://github.com/tiiuae/ghaf-infra/blob/dc5880513b274adbd3567b8e39a1c0ae4e15350b/terraform/scripts/ubuntu-builder.sh#L67C90-L67C153

**Comment by joinemm** [comment]
> Can you include this same change to the 'azarm' (aarch64 Ubuntu builder) configuration, which is currently in a shell script at: https://github.com/tiiuae/ghaf-infra/blob/dc5880513b274adbd3567b8e39a1c0ae4e15350b/terraform/scripts/ubuntu-builder.sh#L67C90-L67C153

good catch

**Review by henrirosten — APPROVED** [review]

**Comment by henrirosten** [comment]
@joinemm : fine to merge from my behalf. Also, please ping me when the switch happens.

**Review by mnokka — COMMENTED** [review]
Logical change for switch

**Pull request merged**
