### PR TITLE
Update GitHub Actions to Latest Version

### PR DESCRIPTION
**Pull request by ssrcdevops**
### GitHub Actions Version Updates
* **[actions/checkout](https://github.com/actions/checkout)** published a new release **[v4.1.7](https://github.com/actions/checkout/releases/tag/v4.1.7)** on 2024-06-12T19:05:21Z
* **[tj-actions/changed-files](https://github.com/tj-actions/changed-files)** published a new release **[v45.0.1](https://github.com/tj-actions/changed-files/releases/tag/v45.0.1)** on 2024-09-02T00:05:11Z

### CODE REVIEW

**Review by cazfi — APPROVED** [review]

**Review by mkaapu — APPROVED** [review]
Could these tool versions be values of variables, so that you would need to change these version numbers only in one place? Not sure if this can be done, not really used GitHub actions.

**Comment by henrirosten** [comment]
Please make sure this is not merged without testing

**Comment by karim20230** [comment]
> Please make sure this is not merged without testing

tested in my fork https://github.com/karim20230/ghaf-infra
https://github.com/karim20230/ghaf-infra/pull/3

**Comment by henrirosten** [comment]
> > Please make sure this is not merged without testing
> 
> tested in my fork https://github.com/karim20230/ghaf-infra [karim20230#3](https://github.com/karim20230/ghaf-infra/pull/3)

Just for the sake of clarify,
can you give direct links to the github action logs on your repo from successful run with each of the updated action:
- [Check Commit Message](https://github.com/tiiuae/ghaf-infra/blob/03ecbd72451e95b0a0b47318a8afb068118e493c/.github/workflows/check-commit-message.yaml)
- [GitHub Actions Version Updater](https://github.com/tiiuae/ghaf-infra/blob/03ecbd72451e95b0a0b47318a8afb068118e493c/.github/workflows/schedule-update-actions.yml)
- [Run pre-push checks](https://github.com/tiiuae/ghaf-infra/blob/03ecbd72451e95b0a0b47318a8afb068118e493c/.github/workflows/test-ghaf-infra.yml)

**Comment by karim20230** [comment]
> > > Please make sure this is not merged without testing
> > 
> > 
> > tested in my fork https://github.com/karim20230/ghaf-infra [karim20230#3](https://github.com/karim20230/ghaf-infra/pull/3)
> 
> @karim20230: Just for the sake of clarify, can you give direct links to the github action logs on your repo from successful run with each of the updated action:
> 
>     * [Check Commit Message](https://github.com/tiiuae/ghaf-infra/blob/03ecbd72451e95b0a0b47318a8afb068118e493c/.github/workflows/check-commit-message.yaml)
> 
>     * [GitHub Actions Version Updater](https://github.com/tiiuae/ghaf-infra/blob/03ecbd72451e95b0a0b47318a8afb068118e493c/.github/workflows/schedule-update-actions.yml)
> 
>     * [Run pre-push checks](https://github.com/tiiuae/ghaf-infra/blob/03ecbd72451e95b0a0b47318a8afb068118e493c/.github/workflows/test-ghaf-infra.yml)

well you can see the logs from here ? it's same fails as here, basically commit msg , sign-off etc please look https://github.com/karim20230/ghaf-infra/actions/runs/10809635345

**Comment by karim20230** [comment]
> > > Please make sure this is not merged without testing
> > 
> > 
> > tested in my fork https://github.com/karim20230/ghaf-infra [karim20230#3](https://github.com/karim20230/ghaf-infra/pull/3)
> 
> @karim20230: Just for the sake of clarify, can you give direct links to the github action logs on your repo from successful run with each of the updated action:
> 
>     * [Check Commit Message](https://github.com/tiiuae/ghaf-infra/blob/03ecbd72451e95b0a0b47318a8afb068118e493c/.github/workflows/check-commit-message.yaml)
> 
>     * [GitHub Actions Version Updater](https://github.com/tiiuae/ghaf-infra/blob/03ecbd72451e95b0a0b47318a8afb068118e493c/.github/workflows/schedule-update-actions.yml)
> 
>     * [Run pre-push checks](https://github.com/tiiuae/ghaf-infra/blob/03ecbd72451e95b0a0b47318a8afb068118e493c/.github/workflows/test-ghaf-infra.yml)

another one I see  

Run if [ "true" == "true" ]; then
Error:  This change edits workflow file '.github/workflows/test-ghaf-infra.yml'. Raising this error to notify that the workflow change will only take impact after merge. Therefore, you need to manually test the change (perhaps in a forked repo)  before merging to make sure the change does not break anything.
Error: Process completed with exit code 1.

**Comment by karim20230** [comment]
And I also take a look on ghafscan how we deal with remote user, auto scan etc, then I noticed seems we don't use commit msg or sign-off checker there

**Comment by karim20230** [comment]
tested and passed https://github.com/karim20230/ghaf-infra/actions/runs/10848504614/job/30107130409?pr=4

**Pull request merged**
