### PR TITLE
Add nix-eval-jobs to jenkins path

### PR DESCRIPTION
**Pull request by joinemm**
Required for parallel building

### CODE REVIEW

**Comment by flokli** [comment]
Can you provide some more context?

**Review by cazfi — DISMISSED** [review]
Likely has a textual conflict with https://github.com/tiiuae/ghaf-infra/pull/246 Agree on the order these PRs should go in, and make them apply properly in that order.

**Comment by joinemm** [comment]
@flokli the context is this pipeline PR https://github.com/tiiuae/ghaf-jenkins-pipeline/pull/70

**Review by henrirosten — DISMISSED** [review]

**Comment by joinemm** [comment]
rebased to fix merge conflict

**Pull request merged**
